* :doc:`/almacen/introduccion`
* :doc:`/almacen/asistente_creacion_de_almacen`
* :doc:`/almacen/datos_principales`
	* :doc:`/almacen/estanterias`
	* :doc:`/almacen/terceros`
	* :doc:`/almacen/configuracion`

* :doc:`/almacen/coleccion_de_ubicaciones`
* :doc:`/almacen/mapa_de_almacen`
* :doc:`/almacen/consultas`
* :doc:`/almacen/dispositivos`
* :doc:`/almacen/etiquetas`
* :doc:`/almacen/impresoras`
* :doc:`/almacen/manipuladores`   `